trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'az-cicd-agent'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration Release
  displayName: 'Build Solution'

- script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Your-Service-Connection'
#     appName: 'Your-WebApp-Name'
#     package: $(Build.ArtifactStagingDirectory)
